[package]
name = "tcp-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
etherparse = "0.19.0"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "sync", "time"] }
tun-rs = { version = "2.7.3", features = ["async_tokio"] }
